[package]
name = "xplatform-memory"
version = "0.2.4"
edition = "2024"

[[bin]]
name = "tfoc"
path = "src/bin/tfoc.rs"

[[bin]]
name = "twfc"
path = "src/bin/twfc.rs"

[[bin]]
name = "openttd"
path = "src/bin/openttd.rs"

[[bin]]
name = "test"
path = "src/bin/test.rs"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
nix = { version = "0.31.2", features = ["process", "ptrace"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = [
  "handleapi",
  "memoryapi",
  "processthreadsapi",
  "psapi",
  "winnt",
  "winuser",
] }

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
owo-colors = "4"
chrono = "0.4"
